### ISSUE TITLE
support for mulit-ami clusters

### ISSUE THREAD

**Issue by isaaguilar** [lannparty/k8s-cluster-update-controller#2]

**Comment by lannparty** [comment]
An approach to this can be making desired image labels a comma separated string that defaults to ignore masters instead of a string concatenation in controller.go.
The default values can be to ignore masters.

**Comment by lannparty** [comment]
Added in https://github.com/lannparty/k8s-cluster-update-controller/pull/8
Just add more images into the comma separated list.
